name: Terraform Apply

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    paths: ["apps/terraform/**"]

jobs:
  apply:
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Connect Tailnet
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TAILSCALE_AUDIENCE }}
          tags: tag:github-actions
          ping: ${{ secrets.INFISICAL_DOMAIN }}

      - name: Get secrets from Infisical
        uses: Infisical/secrets-action@v1.0.15
        with:
          method: oidc
          domain: https://${{ secrets.INFISICAL_DOMAIN }}
          identity-id: ${{ secrets.INFISICAL_IDENTITY_ID }}
          project-slug: terraform
          env-slug: prod

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./apps/terraform

      - name: Find Plan Workflow Run
        if: github.event_name == 'pull_request'
        id: find-run
        uses: actions/github-script@v7
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'terraform-plan.yaml',
              head_sha: '${{ github.event.pull_request.head.sha }}',
              status: 'success',
            });
            core.setOutput('run-id', runs.data.workflow_runs[0].id);

      - name: Download Plan Artifact
        if: github.event_name == 'pull_request'
        uses: actions/download-artifact@v4
        with:
          name: tfplan-pr-${{ github.event.pull_request.number }}
          path: apps/terraform
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.find-run.outputs.run-id }}

      - name: Terraform Apply
        run: terraform apply -no-color ${{ github.event_name == 'pull_request' && 'tfplan' || '-auto-approve' }}
        working-directory: ./apps/terraform
